name: Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Wait for Test
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          checkName: test
          token: ${{ github.token }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        run: python MicrosoftRewardsBot.py --accounts ${{ secrets.ACCOUNTS }} --proxies ${{ secrets.PROXIES }} --headless --fast
