name: Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.0.2
      
      - name: Set up Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.x"
      
      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles("**/requirements.txt") }}
          restore-keys: ${{ runner.os }}-pip-
      
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != "true"
        run: pip install -r requirements.txt
      
      - name: Run Script
        run: python MicrosoftRewardsBot.py --headless
